trigger: none

pool: appagent

stages:
  - stage: BuildStage
    displayName: Build Stage
    jobs:
    - job: BuildJob
      displayName: Build Job
      steps: 
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '16.x'
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: '$(System.DefaultWorkingDirectory)'
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: '$(System.DefaultWorkingDirectory)'
          customCommand: 'run build'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/build'
          artifact: 'elearn'
          publishLocation: 'pipeline'

  - stage: DeployStage
    jobs: 
    - job: DeployJob
      steps: 
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'elearn'
          targetPath: '$(Build.ArtifactStagingDirectory)'
      - task: SSH@0
        inputs:
          sshEndpoint: 'elearns'
          runOptions: 'commands'
          commands: |
            sudo mkdir -p /var/www/html
            sudo chmod -R 777 /var/www/html
            sudo rm -rf /var/www/html/*
          readyTimeout: '20000'
      - task: CopyFilesOverSSH@0
        inputs:
          sshEndpoint: 'elearns'
          sourceFolder: '$(Build.ArtifactStagingDirectory)'
          contents: '**'
          targetFolder: '/var/www/html'
          readyTimeout: '20000'