pool: Self-agent

trigger: none

jobs:
- job: TerraformInstallerJob
  displayName: terraform_installer
  steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

- job: TerraformInitPlanJob
  displayName: terraform init & plan
  dependsOn: TerraformInstallerJob
  steps:
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/2411TF/ENVIRONMENTS/DEV'
      backendServiceArm: 'pipelineapp sc'
      backendAzureRmResourceGroupName: 'skdmp'
      backendAzureRmStorageAccountName: 'skdmpstg'
      backendAzureRmContainerName: 'azcontainer'
      backendAzureRmKey: 'terraform.tfstate'
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/2411TF/ENVIRONMENTS/DEV'
      environmentServiceNameAzureRM: 'pipelineapp sc'

- job: ManualValidationJob
  displayName: manual validation
  dependsOn: TerraformInitPlanJob
  pool: server
  steps: 
  - task: ManualValidation@1
    inputs:
      notifyUsers: 'echo pipe@abc.com'
      instructions: 'please validate the plan'

- job: TerraformInitPlanApplyJob
  displayName: terraformInitPlanApply
  dependsOn: ManualValidationJob
  steps:
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/2411TF/ENVIRONMENTS/DEV'
      backendServiceArm: 'pipelineapp sc'
      backendAzureRmResourceGroupName: 'skdmp'
      backendAzureRmStorageAccountName: 'skdmpstg'
      backendAzureRmContainerName: 'azcontainer'
      backendAzureRmKey: 'terraform.tfstate'
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/2411TF/ENVIRONMENTS/DEV'
      environmentServiceNameAzureRM: 'pipelineapp sc'
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/2411TF/ENVIRONMENTS/DEV'
      environmentServiceNameAzureRM: 'pipelineapp sc'